In [ ]:
#go to documentation of loss functions  ---- https://pytorch.org/docs/stable/nn.html#loss-functions

In [11]:
import torch
import torch.nn as nn

In [31]:
pred = torch.randn(4,5)
print(pred)

tensor([[-1.2216,  0.2844, -1.5690,  1.0068, -0.3407],
        [-0.2544, -0.3441,  0.7546,  1.5141, -0.0505],
        [ 0.2554, -0.7698,  0.0421,  0.1288,  0.0899],
        [ 1.6311,  1.1587, -0.1275, -0.6875, -0.5922]])


In [33]:
label = torch.randn(4,5)
print(label)

tensor([[-1.0420,  1.0089, -0.8899,  1.7082,  0.0460],
        [-1.1091,  1.3561,  1.8723,  0.1703, -0.7455],
        [ 0.4266,  0.9298, -1.2204, -1.0248, -0.3711],
        [-0.9037, -0.7180,  1.8989, -0.5040, -0.6609]])


In [58]:
mse = torch.nn.MSELoss(reduction='mean')

In [60]:
loss = mse(pred , label)
print(loss)

tensor(1.4483)


In [62]:
#mse in python
((pred-label)**2).mean()

tensor(1.4483)

In [81]:
label0 = torch.zeros(4,5).random_(0,2)
label0

tensor([[1., 0., 0., 1., 0.],
        [1., 0., 1., 1., 0.],
        [0., 0., 0., 0., 1.],
        [1., 1., 0., 1., 1.]])

In [ ]:
sigmoid = nn.Sigmoid()