In [1]:
import torch

In [2]:
import numpy as np

In [3]:
a = torch.tensor([2,2,1])
print(a)

tensor([2, 2, 1])


In [4]:
b = torch.tensor([[1,2,3], [4,7,8] , [11,2,55]])

In [5]:
print(a.shape)
print(a.size())

torch.Size([3])
torch.Size([3])


In [6]:
c = torch.FloatTensor([[1,2,3], [4,7,8] , [11,2,55]])

In [7]:
print(b.view(-1,1)) # -1 figures out the required dimension itself
# b = (b.view(-1,1) possible

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 7],
        [ 8],
        [11],
        [ 2],
        [55]])


In [8]:
threeD = torch.randn(2,3,4)
print(threeD)
print(type(threeD))

tensor([[[ 2.0479, -0.3020,  2.0044, -0.1300],
         [ 0.9332, -0.8251, -0.0837,  0.1135],
         [ 0.8530,  1.1608, -1.1628,  0.0386]],

        [[ 1.6475, -0.6052, -1.3847, -1.1973],
         [ 1.1427, -0.8079, -1.1441, -0.6520],
         [-0.7604,  0.9694, -0.2762,  0.5961]]])
<class 'torch.Tensor'>


In [9]:
inarr = torch.randint(6,10,(5,))
print(inarr)
print(inarr.dtype)

tensor([6, 8, 7, 6, 9])
torch.int64


In [10]:
print(torch.numel(inarr))

5


In [11]:
z = torch.zeros(3,3)
o = torch.ones(2,2)
print(z , o)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) tensor([[1., 1.],
        [1., 1.]])


In [12]:
ao = o.numpy()
print(ao)
o.add_(1)
print(o)
print(ao)

[[1. 1.]
 [1. 1.]]
tensor([[2., 2.],
        [2., 2.]])
[[2. 2.]
 [2. 2.]]


In [13]:
fa = np.ones(5)
print(fa)
ts = torch.from_numpy(fa)
print(ts)
np.add(fa ,1 , out = fa)
print(fa)
print(ts)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
#cuda

In [15]:
l = [2,3,4,5]
to_list = torch.tensor(l)
print(to_list)

tensor([2, 3, 4, 5])


In [27]:
first = torch.randn(2,5)
second = torch.randn(3,5)
con1 = torch.cat([first , second])
print(first)
print(second)
print(con1)

tensor([[-1.1349,  0.7233, -0.6192,  1.7935, -0.0526],
        [ 0.2190,  0.0789, -1.0947, -1.0166, -0.8729]])
tensor([[-1.3235, -0.5728,  0.3216,  0.6369, -2.2955],
        [-0.5315, -1.1742, -0.8463,  0.1914, -0.3527],
        [-0.3610,  0.1589, -0.6193, -0.2063, -1.5393]])
tensor([[-1.1349,  0.7233, -0.6192,  1.7935, -0.0526],
        [ 0.2190,  0.0789, -1.0947, -1.0166, -0.8729],
        [-1.3235, -0.5728,  0.3216,  0.6369, -2.2955],
        [-0.5315, -1.1742, -0.8463,  0.1914, -0.3527],
        [-0.3610,  0.1589, -0.6193, -0.2063, -1.5393]])


In [39]:
tensor_1 = torch.tensor([[1, 2, 3, 4],[6,7,8,9]])
tensor_a = torch.unsqueeze(tensor_1, 0)
print(tensor_a)

tensor([[[1, 2, 3, 4],
         [6, 7, 8, 9]]])


In [41]:
#Remember, If requires_grad=True, the Tensor object keeps track of how it was created.
x = torch.tensor([1., 2., 3], requires_grad=True)
y = torch.tensor([4., 5., 6], requires_grad=True)
#Notice that both x and y have their required_grad set to true, therefore we an compute gradients with respect to them
z = x + y
print(z)
# z knows that is was created as a result of addition of x and y. It knows that it wasn't read in from a file
print(z.grad_fn)
#And if we go further on this
s = z.sum()
print(s)
print(s.grad_fn)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)
tensor(21., grad_fn=<SumBackward0>)


In [47]:
s.backward()
print(x.grad)

tensor([2., 2., 2.])


In [ ]:
#Remember, If requires_grad=True, the Tensor object keeps track of how it was created.
x = torch.tensor([1., 2., 3], requires_grad=True)
y = torch.tensor([4., 5., 6], requires_grad=True)
#Notice that both x and y have their required_grad set to true, therefore we an compute gradients with respect to them
z = x + y
print(z)
# z knows that is was created as a result of addition of x and y. It knows that it wasn't read in from a file
print(z.grad_fn)
#And if we go further on this
s = z.sum()
print(s)
print(s.grad_fn)