In [ ]:
# wieght initilization https://pytorch.org/docs/stable/nn.init.html#torch.nn.init.uniform_

In [1]:
import torch 
import torch.nn as nn

In [3]:
layer = nn.Linear(5,5)

In [11]:
print(layer.weight)

Parameter containing:
tensor([[-0.4438,  0.3959, -0.0465, -0.1749, -0.0568],
        [-0.3617,  0.0580, -0.3535,  0.0810,  0.4364],
        [ 0.1988, -0.4456, -0.2978, -0.2096,  0.3230],
        [-0.0589, -0.0729,  0.1991, -0.2337,  0.2379],
        [-0.3837,  0.4339,  0.1316, -0.1610,  0.1662]], requires_grad=True)


In [30]:
torch.nn.init.uniform_(layer.weight, a=0.0, b=3.0, generator=None)

Parameter containing:
tensor([[2.6658, 0.3266, 0.1356, 0.0389, 1.8907],
        [2.5012, 0.6768, 1.9795, 2.3481, 1.0710],
        [0.2518, 0.1424, 1.7857, 0.3791, 0.2323],
        [0.1054, 2.7240, 2.1900, 0.6961, 1.3072],
        [0.3866, 2.5829, 1.2070, 2.5607, 2.3733]], requires_grad=True)

In [37]:
torch.nn.init.normal_(layer.weight, mean=0.0, std=1.0, generator=None)

Parameter containing:
tensor([[-0.4747, -0.4968, -0.5173,  1.8801,  1.6839],
        [-2.3123, -0.8341, -0.4870, -0.9279,  0.4503],
        [ 1.0962,  0.7558,  0.4729,  0.0615, -1.0742],
        [-0.9688, -0.2460, -1.7820,  0.2152, -1.0891],
        [-0.3140, -2.2577,  0.8867,  0.2656,  0.3595]], requires_grad=True)

In [49]:
print(type(layer.weight))

<class 'torch.nn.parameter.Parameter'>
